// Generated by scripts/generate-filebrowser-locales.mjs from File Browser
// commit 833d908884d5c801f30f5c098d7977177eb3a36b (Apache-2.0). Do not edit by hand.

export const fileBrowserTranslations = {
  "ar": {
    "translation": {
      "nav": {
        "files": "الملفات",
        "settings": "اﻹعدادات",
        "logout": "تسجيل خروج"
      },
      "auth": {
        "username": "إسم المستخدم",
        "password": "كلمة المرور",
        "signIn": "تسجيل دخول",
        "failed": "بيانات دخول خاطئة",
        "newPassword": "كلمة المرور الجديدة",
        "confirmPassword": "تأكيد كلمة المرور"
      },
      "files": {
        "search": "البحث...",
        "upload": "رفع",
        "newFolder": "مجلد جديد",
        "empty": "تبدو وحيدا هنا...",
        "name": "اﻹسم",
        "size": "الحجم",
        "modified": "آخر تعديل",
        "preview": "معاينة",
        "edit": "تعديل على شكل نص",
        "rename": "إعادة تسمية",
        "move": "نقل",
        "copy": "نسخ",
        "delete": "حذف",
        "download": "تحميل",
        "share": "مشاركة",
        "save": "حفظ التغييرات",
        "editor": "تعديل على شكل نص",
        "noPreview": "لا يوجد عرض مسبق لهذا الملف.",
        "clearSearch": "مسح"
      },
      "shares": {
        "title": "إدارة المشاركات",
        "path": "المسار",
        "password": "كلمة مرور إختيارية",
        "copy": "نسخ رابط التحميل الى الحافظة",
        "download": "تحميل"
      },
      "settings": {
        "title": "اﻹعدادات",
        "theme": "موضوع",
        "language": "اللغة",
        "light": "فاتح",
        "dark": "غامق",
        "system": "افتراضي (نظام التشغيل)",
        "password": "تغيير كلمة المرور",
        "newPassword": "كلمة المرور الجديدة",
        "changePassword": "تغيير كلمة المرور",
        "save": "حفظ"
      },
      "common": {
        "cancel": "إلغاء",
        "create": "إنشاء",
        "close": "إغلاق",
        "confirm": "موافق",
        "loading": "جاري التحميل...",
        "copied": "تم نسخ الملف",
        "error": "لقد حدث خطأ ما"
      }
    }
  },
  "bg": {
    "translation": {
      "nav": {
        "files": "Файлове",
        "settings": "Настройки",
        "logout": "Изход"
      },
      "auth": {
        "username": "Потребителско име",
        "password": "Парола",
        "signIn": "Вход",
        "failed": "Грешни потребителско име и/или парола",
        "newPassword": "Вашата нова парола",
        "confirmPassword": "Потвърди вашата нова парола"
      },
      "files": {
        "search": "Търсене ...",
        "upload": "Качи",
        "newFolder": "Нова папка",
        "empty": "Тук е самотно ...",
        "name": "Име",
        "size": "Размер",
        "modified": "Последна промяна",
        "preview": "Преглед",
        "rename": "Преименуване",
        "move": "Премести",
        "copy": "Копирай",
        "delete": "Изтрий",
        "download": "Свали",
        "share": "Сподели",
        "save": "Запиши промените",
        "noPreview": "За този файл не е наличен преглед.",
        "clearSearch": "Изчисти"
      },
      "shares": {
        "title": "Управление на споделянето",
        "path": "Път",
        "password": "Опционална парола",
        "copy": "Копирай линк за сваляне в клипборда",
        "download": "Свали"
      },
      "settings": {
        "title": "Настройки",
        "theme": "Тема",
        "language": "Език",
        "light": "Светла",
        "dark": "Тъмна",
        "system": "Настройки по подразбиране",
        "password": "Промени парола",
        "newPassword": "Вашата нова парола",
        "changePassword": "Промени парола",
        "save": "Запис"
      },
      "common": {
        "cancel": "Отмени",
        "create": "Създай",
        "close": "Затвори",
        "confirm": "Потвърди",
        "loading": "Зареждане ...",
        "copied": "Връзката е копирана!",
        "error": "Възникна грешка"
      }
    }
  },
  "ca": {
    "translation": {
      "nav": {
        "files": "Fitxers",
        "settings": "Ajustos",
        "logout": "Tancar sessió"
      },
      "auth": {
        "username": "Usuari",
        "password": "Contrasenya",
        "signIn": "Iniciar sessió",
        "failed": "Usuari i/o contrasenya incorrectes",
        "newPassword": "La teva nova contrasenya",
        "confirmPassword": "Confirma la teva contrasenya"
      },
      "files": {
        "search": "Cercar...",
        "upload": "Pujar",
        "newFolder": "Nova carpeta",
        "empty": "Un se sent molt sol aquí...",
        "name": "Nom",
        "size": "Mida",
        "modified": "Última modificació",
        "rename": "Reanomenar",
        "move": "Moure",
        "copy": "Copiar",
        "delete": "Esborrar",
        "download": "Descarregar",
        "share": "Compartir",
        "noPreview": "La vista prèvia no està disponible per a aquest fitxer.",
        "clearSearch": "Netejar"
      },
      "shares": {
        "title": "Gestió Compartida",
        "path": "Ruta",
        "password": "Contrasenya opcional",
        "copy": "Copiar l'enllaç de descàrrega al portapapers",
        "download": "Descarregar"
      },
      "settings": {
        "title": "Ajustos",
        "theme": "Tema",
        "language": "Idioma",
        "light": "Clar",
        "dark": "Fosc",
        "system": "Valor per defecte del sistema",
        "password": "Canviar contrasenya",
        "newPassword": "La teva nova contrasenya",
        "changePassword": "Canviar contrasenya",
        "save": "Desar"
      },
      "common": {
        "cancel": "Cancel·lar",
        "create": "Crear",
        "close": "Tancar",
        "confirm": "D'acord",
        "loading": "Carregant...",
        "copied": "Enllaç copiat!",
        "error": "Alguna cosa ha fallat"
      }
    }
  },
  "cs": {
    "translation": {
      "nav": {
        "files": "Soubory",
        "settings": "Nastavení",
        "logout": "Odhlásit se"
      },
      "auth": {
        "username": "Uživatelské jméno",
        "password": "Heslo",
        "signIn": "Přihlásit se",
        "failed": "Nesprávné přihlašovací údaje",
        "newPassword": "Vaše nové heslo",
        "confirmPassword": "Potvrďte své nové heslo"
      },
      "files": {
        "search": "Hledat...",
        "upload": "Nahrát",
        "newFolder": "Nová složka",
        "empty": "Je tu osaměle...",
        "name": "Název",
        "size": "Velikost",
        "modified": "Naposledy změněno",
        "rename": "Přejmenovat",
        "move": "Přesunout",
        "copy": "Kopírovat",
        "delete": "Smazat",
        "download": "Stáhnout",
        "share": "Sdílet",
        "noPreview": "Náhled pro tento soubor není k dispozici.",
        "clearSearch": "Vymazat"
      },
      "shares": {
        "title": "Správa sdílení",
        "path": "Cesta",
        "password": "Volitelné heslo",
        "copy": "Kopírovat odkaz na stažení do schránky",
        "download": "Stáhnout"
      },
      "settings": {
        "title": "Nastavení",
        "theme": "Motiv",
        "language": "Jazyk",
        "light": "Světlý",
        "dark": "Tmavý",
        "system": "Systémové výchozí",
        "password": "Změnit heslo",
        "newPassword": "Vaše nové heslo",
        "changePassword": "Změnit heslo",
        "save": "Uložit"
      },
      "common": {
        "cancel": "Zrušit",
        "create": "Vytvořit",
        "close": "Zavřít",
        "loading": "Načítání...",
        "copied": "Odkaz zkopírován!",
        "error": "Něco se pokazilo"
      }
    }
  },
  "de": {
    "translation": {
      "nav": {
        "files": "Dateien",
        "settings": "Einstellungen",
        "logout": "Abmelden"
      },
      "auth": {
        "username": "Benutzername",
        "password": "Passwort",
        "signIn": "Anmelden",
        "failed": "Falsche Anmeldedaten",
        "newPassword": "Dein neues Passwort",
        "confirmPassword": "Neues Passwort bestätigen"
      },
      "files": {
        "search": "Suchen …",
        "upload": "Hochladen",
        "newFolder": "Neuer Ordner",
        "empty": "Hier ist es ganz schön leer …",
        "size": "Größe",
        "modified": "Zuletzt geändert",
        "preview": "Vorschau",
        "edit": "Als Text bearbeiten",
        "rename": "Umbenennen",
        "move": "Verschieben",
        "copy": "Kopieren",
        "delete": "Löschen",
        "download": "Herunterladen",
        "share": "Teilen",
        "save": "Änderungen speichern",
        "editor": "Als Text bearbeiten",
        "noPreview": "Für diese Datei ist keine Vorschau verfügbar.",
        "clearSearch": "Leeren"
      },
      "shares": {
        "title": "Freigabeverwaltung",
        "path": "Pfad",
        "password": "Optionales Passwort",
        "copy": "Download-Link in Zwischenablage kopieren",
        "download": "Herunterladen"
      },
      "settings": {
        "title": "Einstellungen",
        "theme": "Design",
        "language": "Sprache",
        "light": "Hell",
        "dark": "Dunkel",
        "system": "Systemstandard",
        "password": "Passwort ändern",
        "currentPassword": "Dein aktuelles Passwort",
        "newPassword": "Dein neues Passwort",
        "changePassword": "Passwort ändern",
        "save": "Speichern"
      },
      "common": {
        "cancel": "Abbrechen",
        "create": "Erstellen",
        "close": "Schließen",
        "loading": "Wird geladen …",
        "copied": "Link kopiert!",
        "error": "Etwas ist schiefgelaufen"
      }
    }
  },
  "el": {
    "translation": {
      "nav": {
        "files": "Αρχεία",
        "settings": "Ρυθμίσεις",
        "logout": "Αποσύνδεση"
      },
      "auth": {
        "username": "Όνομα χρήστη",
        "password": "Κωδικός πρόσβασης",
        "signIn": "Είσοδος",
        "failed": "Λάθος όνομα ή/και κωδικός πρόσβασης",
        "newPassword": "Νέος κωδικός πρόσβασης",
        "confirmPassword": "Επιβεβαιώστε τον νέο κωδικό πρόσβασης"
      },
      "files": {
        "search": "Αναζήτηση…",
        "upload": "Μεταφόρτωση",
        "newFolder": "Νέος φάκελος",
        "empty": "Δεν υπάρχει τίποτα εδώ (ακόμη)…",
        "name": "Όνομα",
        "size": "Μέγεθος",
        "modified": "Τελευταία τροποποίηση",
        "rename": "Μετονομασία",
        "move": "Μετακίνηση",
        "copy": "Αντιγραφή",
        "delete": "Διαγραφή",
        "download": "Λήψη",
        "share": "Κοινοποίηση",
        "noPreview": "Η προεπισκόπηση δεν είναι διαθέσιμη για αυτό το αρχείο.",
        "clearSearch": "Καθαρισμός"
      },
      "shares": {
        "title": "Διαχείριση κοινοποίησης",
        "path": "Διαδρομή",
        "password": "Προαιρετικός κωδικός πρόσβασης",
        "copy": "Αντιγραφή συνδέσμου λήψης στο πρόχειρο",
        "download": "Λήψη"
      },
      "settings": {
        "title": "Ρυθμίσεις",
        "theme": "Μοτίβο",
        "language": "Γλώσσα",
        "light": "Φωτεινό",
        "dark": "Σκοτεινό",
        "password": "Αλλαγή κωδικού πρόσβασης",
        "newPassword": "Νέος κωδικός πρόσβασης",
        "changePassword": "Αλλαγή κωδικού πρόσβασης",
        "save": "Αποθήκευση"
      },
      "common": {
        "cancel": "Ακύρωση",
        "create": "Δημιουργία",
        "close": "Κλείσιμο",
        "confirm": "Εντάξει",
        "loading": "Φορτώνει…",
        "copied": "Ο σύνδεσμος αντιγράφηκε!",
        "error": "Προέκυψε κάποιο σφάλμα"
      }
    }
  },
  "es": {
    "translation": {
      "nav": {
        "files": "Archivos",
        "settings": "Ajustes",
        "logout": "Cerrar sesión"
      },
      "auth": {
        "username": "Usuario",
        "password": "Contraseña",
        "signIn": "Iniciar sesión",
        "failed": "Usuario y/o contraseña incorrectos",
        "newPassword": "Tu nueva contraseña",
        "confirmPassword": "Confirma tu contraseña"
      },
      "files": {
        "search": "Buscar...",
        "upload": "Subir",
        "newFolder": "Nueva carpeta",
        "empty": "Uno se siente muy sólo aquí...",
        "name": "Nombre",
        "size": "Tamaño",
        "modified": "Última modificación",
        "rename": "Renombrar",
        "move": "Mover",
        "copy": "Copiar",
        "delete": "Borrar",
        "download": "Descargar",
        "share": "Compartir",
        "save": "Guardar cambios",
        "noPreview": "La vista previa no está disponible para este archivo.",
        "clearSearch": "Limpiar"
      },
      "shares": {
        "title": "Gestión Compartida",
        "path": "Ruta",
        "password": "Contraseña opcional",
        "copy": "Copiar enlace de descarga al portapapeles",
        "download": "Descargar"
      },
      "settings": {
        "title": "Ajustes",
        "theme": "Tema",
        "language": "Idioma",
        "light": "Claro",
        "dark": "Oscuro",
        "password": "Cambiar contraseña",
        "newPassword": "Tu nueva contraseña",
        "changePassword": "Cambiar contraseña",
        "save": "Guardar"
      },
      "common": {
        "cancel": "Cancelar",
        "create": "Crear",
        "close": "Cerrar",
        "loading": "Cargando...",
        "copied": "¡Link copiado!",
        "error": "Algo ha fallado"
      }
    }
  },
  "fa": {
    "translation": {
      "nav": {
        "files": "فایل ها",
        "settings": "تنظیمات",
        "logout": "خروج از حساب"
      },
      "auth": {
        "username": "نام کاربری",
        "password": "رمز عبور",
        "signIn": "ورود",
        "failed": "خطا در اعتبارسنجی",
        "newPassword": "رمز جدید شما",
        "confirmPassword": "تایید رمز جدید شما"
      },
      "files": {
        "search": "جستجو...",
        "upload": "آپلود",
        "newFolder": "پوشه جدید",
        "name": "نام",
        "size": "اندازه",
        "modified": "آخرین ویرایش",
        "preview": "نمایش",
        "rename": "تغییر نام",
        "move": "انتقال",
        "copy": "کپی",
        "delete": "حذف",
        "download": "دانلود",
        "share": "اشتراک گذاری",
        "noPreview": "این فایل قابل نمایش نیست",
        "clearSearch": "پاک کردن"
      },
      "shares": {
        "title": "مدیریت به اشتراک گذاری",
        "path": "مسیر",
        "password": "رمز عبور اختیاری",
        "copy": "کپی آدرس به حافظه",
        "download": "دانلود"
      },
      "settings": {
        "title": "تنظیمات",
        "theme": "تم یا زمینه",
        "language": "زبان",
        "light": "روشن",
        "dark": "تاریک ",
        "system": "تنظیمات پیش فرض سیستم",
        "password": "تعبیر رمز",
        "newPassword": "رمز جدید شما",
        "changePassword": "تعبیر رمز",
        "save": "ذخیره"
      },
      "common": {
        "cancel": "لغو",
        "create": "ایجاد",
        "close": "بستن",
        "confirm": "تایید",
        "loading": "در حال بارگذاری...",
        "copied": "لینک کپی شد!",
        "error": "اشتباهی رخ داده"
      }
    }
  },
  "fr": {
    "translation": {
      "nav": {
        "files": "Fichiers",
        "settings": "Paramètres",
        "logout": "Se déconnecter"
      },
      "auth": {
        "username": "Identifiant",
        "password": "Mot de passe",
        "signIn": "Se connecter",
        "failed": "Identifiants incorrects !",
        "newPassword": "Votre nouveau mot de passe",
        "confirmPassword": "Confirmation du nouveau mot de passe"
      },
      "files": {
        "search": "Recherche en cours...",
        "upload": "Importer",
        "newFolder": "Nouveau dossier",
        "empty": "C'est un peu désert ici...",
        "name": "Nom",
        "size": "Taille",
        "modified": "Dernière modification",
        "preview": "Prévisualiser",
        "edit": "Editer comme Texte",
        "rename": "Renommer",
        "move": "Déplacer",
        "copy": "Copier",
        "delete": "Supprimer",
        "download": "Télécharger",
        "share": "Partager",
        "save": "Enregistrer changements",
        "editor": "Editer comme Texte",
        "noPreview": "L'aperçu n'est pas disponible pour ce fichier.",
        "clearSearch": "Effacer"
      },
      "shares": {
        "title": "Gestion des partages",
        "path": "Chemin",
        "password": "Mot de passe optionnel",
        "copy": "Copier le lien de téléchargement dans le presse-papier",
        "download": "Télécharger"
      },
      "settings": {
        "title": "Paramètres",
        "theme": "Thème",
        "language": "Langue",
        "light": "Clair",
        "dark": "Sombre",
        "system": "Par défaut du système",
        "password": "Modifier le mot de passe",
        "currentPassword": "Mot de Passe Actuel",
        "newPassword": "Votre nouveau mot de passe",
        "changePassword": "Modifier le mot de passe",
        "save": "Enregistrer"
      },
      "common": {
        "cancel": "Annuler",
        "create": "Créer",
        "close": "Fermer",
        "loading": "Chargement...",
        "copied": "Lien copié !",
        "error": "Quelque chose s'est mal passé"
      }
    }
  },
  "he": {
    "translation": {
      "nav": {
        "files": "קבצים",
        "settings": "הגדרות",
        "logout": "התנתק"
      },
      "auth": {
        "username": "שם משתמש",
        "password": "סיסמא",
        "signIn": "התחברות",
        "failed": "פרטי התחברות שגויים",
        "newPassword": "הסיסמא החדשה שלך",
        "confirmPassword": "אשר את הסיסמה החדשה שלך"
      },
      "files": {
        "search": "חיפוש...",
        "upload": "העלאה",
        "newFolder": "תיקייה חדשה",
        "empty": "בודד כאן",
        "name": "שם",
        "size": "גודל",
        "modified": "שונה לאחרונה",
        "rename": "שינוי שם",
        "move": "העברה",
        "copy": "העתקה",
        "delete": "מחק",
        "download": "הורדה",
        "share": "שיתוף",
        "noPreview": "לא זמינה תצוגה מקדימה לקובץ זה",
        "clearSearch": "נקה"
      },
      "shares": {
        "title": "ניהול שיתוף",
        "path": "נתיב",
        "password": "סיסמא אופציונלית",
        "copy": "העתק קישור הורדה ללוח",
        "download": "הורדה"
      },
      "settings": {
        "title": "הגדרות",
        "theme": "ערכת נושא",
        "language": "שפה",
        "light": "בהיר",
        "dark": "כהה",
        "password": "שינוי סיסמא",
        "newPassword": "הסיסמא החדשה שלך",
        "changePassword": "שינוי סיסמא",
        "save": "שמירה"
      },
      "common": {
        "cancel": "ביטול",
        "create": "צור",
        "close": "סגירה",
        "confirm": "אישור",
        "loading": "טוען...",
        "copied": "הקישור הועתק!",
        "error": "משהו השתבש"
      }
    }
  },
  "hr": {
    "translation": {
      "nav": {
        "files": "Datoteke",
        "settings": "Postavke",
        "logout": "Odjava"
      },
      "auth": {
        "username": "Korisničko ime",
        "password": "Lozinka",
        "signIn": "Prijava",
        "failed": "Neispravno korisničko ime/lozinka",
        "newPassword": "Vaša nova lozinka",
        "confirmPassword": "Potvrdite Vašu novu lozinku"
      },
      "files": {
        "search": "Pretraživanje...",
        "upload": "Prenesi",
        "newFolder": "Nova mapa",
        "empty": "Ovdje je tako prazno...",
        "name": "Naziv",
        "size": "Veličina",
        "modified": "Zadnje izmijenjeno",
        "preview": "Pregled",
        "edit": "Uredi kao tekst",
        "rename": "Preimenuj",
        "move": "Premjesti",
        "copy": "Kopiraj",
        "delete": "Izbriši",
        "download": "Preuzmi",
        "share": "Podijeli",
        "save": "Spremi promjene",
        "editor": "Uredi kao tekst",
        "noPreview": "Pregled nije dostupan za ovu datoteku.",
        "clearSearch": "Očisti"
      },
      "shares": {
        "title": "Upravljanje Dijeljenjem",
        "path": "Put",
        "password": "Opcionalna lozinka",
        "copy": "Kopiraj poveznicu za preuzimanje u međuspremnik",
        "download": "Preuzmi"
      },
      "settings": {
        "title": "Postavke",
        "theme": "Tema",
        "language": "Jezik",
        "light": "Svijetlo",
        "dark": "Tamno",
        "system": "Zadano - Sustav",
        "password": "Promjena lozinke",
        "currentPassword": "Vaša trenutna lozinka",
        "newPassword": "Vaša nova lozinka",
        "changePassword": "Promjena lozinke",
        "save": "Spremi"
      },
      "common": {
        "cancel": "Otkaži",
        "create": "Stvori",
        "close": "Zatvori",
        "loading": "Učitavanje...",
        "copied": "Poveznica kopirana!",
        "error": "Nešto je pošlo po zlu"
      }
    }
  },
  "hu": {
    "translation": {
      "nav": {
        "files": "Fájlok",
        "settings": "Beállítások",
        "logout": "Kilépés"
      },
      "auth": {
        "username": "Felhasználói név",
        "password": "Jelszó",
        "signIn": "Belépés",
        "failed": "Hibás hitelesítő adatok",
        "newPassword": "Új jelszó",
        "confirmPassword": "Új jelszó ismét"
      },
      "files": {
        "search": "Keresés…",
        "upload": "Feltöltés",
        "newFolder": "Új mappa",
        "empty": "Ez egy magányos érzés…",
        "name": "Név",
        "size": "Méret",
        "modified": "Utoljára módosítva",
        "rename": "Átnevezés",
        "move": "Mozgatás",
        "copy": "Másolás",
        "delete": "Törlése",
        "download": "Letöltés",
        "share": "Megosztás",
        "noPreview": "Ehhez a fájlhoz nincs előnézet.",
        "clearSearch": "Törlése"
      },
      "shares": {
        "title": "Megosztáskezelés",
        "path": "Elérési útvonal",
        "password": "Választható jelszó",
        "download": "Letöltés"
      },
      "settings": {
        "title": "Beállítások",
        "theme": "Téma",
        "language": "Nyelv",
        "light": "Világos",
        "dark": "Sötét",
        "password": "Jelszó módosítása",
        "newPassword": "Új jelszó",
        "changePassword": "Jelszó módosítása",
        "save": "Mentés"
      },
      "common": {
        "cancel": "Mégse",
        "create": "Létrehozás",
        "close": "Bezárás",
        "loading": "Betöltés…",
        "copied": "Link másolva!",
        "error": "Valami rosszul sült el"
      }
    }
  },
  "is": {
    "translation": {
      "nav": {
        "files": "Skjöl",
        "settings": "Stillingar",
        "logout": "Útskráning"
      },
      "auth": {
        "username": "Notendanafn",
        "password": "Lykilorð",
        "signIn": "Innskráning",
        "failed": "Rangar notendaupplýsingar",
        "newPassword": "Nýja lykilorðið þitt",
        "confirmPassword": "Staðfestu nýja lykilorðið"
      },
      "files": {
        "search": "Leita...",
        "upload": "Hlaða upp",
        "newFolder": "Ný mappa",
        "empty": "Ekkert hér...",
        "name": "Nafn",
        "size": "Stærð",
        "modified": "Seinast breytt",
        "rename": "Endurnefna",
        "move": "Færa",
        "copy": "Afrita",
        "delete": "Eyða",
        "download": "Sækja",
        "share": "Deila",
        "clearSearch": "Hreinsa"
      },
      "shares": {
        "download": "Sækja"
      },
      "settings": {
        "title": "Stillingar",
        "language": "Tungumál",
        "password": "Breyta lykilorði",
        "newPassword": "Nýja lykilorðið þitt",
        "changePassword": "Breyta lykilorði",
        "save": "Vista"
      },
      "common": {
        "cancel": "Hætta við",
        "create": "Búa til",
        "close": "Loka",
        "loading": "Hleð...",
        "copied": "Hlekkur afritaður!",
        "error": "Eitthvað fór úrskeiðis"
      }
    }
  },
  "it": {
    "translation": {
      "nav": {
        "files": "File",
        "settings": "Impostazioni",
        "logout": "Esci"
      },
      "auth": {
        "username": "Nome utente",
        "signIn": "Entra",
        "failed": "Credenziali errate",
        "newPassword": "La tua nuova password",
        "confirmPassword": "Conferma la password"
      },
      "files": {
        "search": "Cerca...",
        "upload": "Carica",
        "newFolder": "Nuova cartella",
        "empty": "Ci si sente soli qui...",
        "name": "Nome",
        "size": "Dimensione",
        "modified": "Ultima modifica",
        "preview": "Anteprima",
        "rename": "Rinomina",
        "move": "Sposta",
        "copy": "Copia",
        "delete": "Elimina",
        "download": "Scarica",
        "share": "Condividi",
        "noPreview": "L'anteprima non è disponibile per questo file.",
        "clearSearch": "Cancella"
      },
      "shares": {
        "title": "Gestione delle condivisioni",
        "path": "Percorso",
        "password": "Password opzionale",
        "copy": "Copia link di scarica negli appunti",
        "download": "Scarica"
      },
      "settings": {
        "title": "Impostazioni",
        "theme": "Tema",
        "language": "Lingua",
        "light": "Chiaro",
        "dark": "Scuro",
        "system": "Impostazione predefinita del sistema",
        "password": "Modifica password",
        "newPassword": "La tua nuova password",
        "changePassword": "Modifica password",
        "save": "Salva"
      },
      "common": {
        "cancel": "Annulla",
        "create": "Crea",
        "close": "Chiudi",
        "loading": "Caricamento...",
        "copied": "Link copiato!",
        "error": "Qualcosa è andato per il verso storto"
      }
    }
  },
  "ja": {
    "translation": {
      "nav": {
        "files": "ファイル",
        "settings": "設定",
        "logout": "ログアウト"
      },
      "auth": {
        "username": "ユーザー名",
        "password": "パスワード",
        "signIn": "ログイン",
        "failed": "ユーザー名またはパスワードが間違っています",
        "newPassword": "新しいパスワード",
        "confirmPassword": "新しいパスワード（再入力）"
      },
      "files": {
        "search": "検索",
        "upload": "アップロード",
        "newFolder": "新規フォルダー",
        "empty": "ここには何もないようです…",
        "name": "名前",
        "size": "サイズ",
        "modified": "更新日時",
        "rename": "名前の変更",
        "move": "移動",
        "copy": "コピー",
        "delete": "削除",
        "download": "ダウンロード",
        "share": "共有",
        "noPreview": "プレビューはこのファイルでは利用できません",
        "clearSearch": "クリアー"
      },
      "shares": {
        "title": "共有の管理",
        "path": "パス",
        "password": "パスワード（オプション）",
        "copy": "ダウンロードリンクをコピー",
        "download": "ダウンロード"
      },
      "settings": {
        "title": "設定",
        "theme": "テーマ",
        "language": "言語",
        "light": "ライト",
        "dark": "ダーク",
        "password": "パスワードの変更",
        "newPassword": "新しいパスワード",
        "changePassword": "パスワードの変更",
        "save": "保存"
      },
      "common": {
        "cancel": "キャンセル",
        "create": "作成",
        "close": "閉じる",
        "loading": "読み込み中…",
        "copied": "リンクをコピーしました！",
        "error": "エラーが発生しました"
      }
    }
  },
  "ko": {
    "translation": {
      "nav": {
        "files": "파일",
        "settings": "설정",
        "logout": "로그아웃"
      },
      "auth": {
        "username": "사용자 이름",
        "password": "비밀번호",
        "signIn": "로그인",
        "failed": "사용자 이름 또는 비밀번호를 확인",
        "newPassword": "새로운 비밀번호",
        "confirmPassword": "새로운 비밀번호 확인"
      },
      "files": {
        "search": "검색...",
        "upload": "업로드",
        "newFolder": "새로운 폴더",
        "empty": "외로워요... (비어 있음)",
        "name": "이름",
        "size": "크기",
        "modified": "최종 수정",
        "preview": "미리보기",
        "edit": "텍스트로 편집",
        "rename": "이름 바꾸기",
        "move": "이동",
        "copy": "복사",
        "delete": "삭제",
        "download": "다운로드",
        "share": "공유",
        "save": "변경사항 저장",
        "editor": "텍스트로 편집",
        "noPreview": "미리 볼 수 없는 파일입니다.",
        "clearSearch": "지우기"
      },
      "shares": {
        "title": "공유 내역 관리",
        "path": "경로",
        "password": "비밀번호 (선택)",
        "copy": "다운로드 링크 복사",
        "download": "다운로드"
      },
      "settings": {
        "title": "설정",
        "theme": "테마",
        "language": "언어",
        "light": "밝은 테마",
        "dark": "어두운 테마",
        "system": "시스템 기본값",
        "password": "비밀번호 변경",
        "currentPassword": "현재 비밀번호",
        "newPassword": "새로운 비밀번호",
        "changePassword": "비밀번호 변경",
        "save": "저장"
      },
      "common": {
        "cancel": "취소",
        "create": "생성",
        "close": "닫기",
        "confirm": "확인",
        "loading": "불러오는 중...",
        "copied": "링크가 복사되었습니다!",
        "error": "에러 발생"
      }
    }
  },
  "lv": {
    "translation": {
      "nav": {
        "files": "Faili",
        "settings": "Iestatījumi",
        "logout": "Atteikties"
      },
      "auth": {
        "username": "Lietotājvārds",
        "password": "Parole",
        "signIn": "Pieteikties",
        "failed": "Nepareizi akreditācijas dati",
        "newPassword": "Jūsu jaunā parole",
        "confirmPassword": "Apstipriniet savu jauno paroli"
      },
      "files": {
        "search": "Meklē...",
        "upload": "Augšupielādēt",
        "newFolder": "Jauna mape",
        "empty": "Šeit ir tukša vieta...",
        "name": "Vārds",
        "size": "Izmērs",
        "modified": "Pēdējoreiz modificēts",
        "preview": "Priekšskatījums",
        "edit": "Rediģēt kā tekstu",
        "rename": "Pārdēvēt",
        "move": "Pārvietot",
        "copy": "Kopēt",
        "delete": "Dzēst",
        "download": "Lejupielādēt",
        "share": "Dalīties",
        "save": "Saglabāt izmaiņas",
        "editor": "Rediģēt kā tekstu",
        "noPreview": "Šim failam nav pieejams priekšskatījums.",
        "clearSearch": "Tīrs"
      },
      "shares": {
        "title": "Kopīgošanas pārvaldība",
        "path": "Ceļš",
        "password": "Izvēles parole",
        "copy": "Kopēt lejupielādes saiti starpliktuvē",
        "download": "Lejupielādēt"
      },
      "settings": {
        "title": "Iestatījumi",
        "theme": "Tēma",
        "language": "Valoda",
        "light": "Gaiša",
        "dark": "Tumša",
        "system": "Sistēmas noklusējums",
        "password": "Mainīt paroli",
        "newPassword": "Jūsu jaunā parole",
        "changePassword": "Mainīt paroli",
        "save": "Saglabāt"
      },
      "common": {
        "cancel": "Atcelt",
        "create": "Izveidot",
        "close": "Aizvērt",
        "confirm": "Labi",
        "loading": "Notiek ielāde...",
        "copied": "Saite nokopēta!",
        "error": "Kaut kas nogāja greizi"
      }
    }
  },
  "nl": {
    "translation": {
      "nav": {
        "files": "Bestanden",
        "settings": "Instellingen",
        "logout": "Uitloggen"
      },
      "auth": {
        "username": "Gebruikersnaam",
        "password": "Wachtwoord",
        "signIn": "Inloggen",
        "failed": "Inloggegevens zijn incorrect",
        "newPassword": "Uw nieuwe wachtwoord",
        "confirmPassword": "Uw nieuwe wachtwoord bevestigen"
      },
      "files": {
        "search": "Zoeken...",
        "upload": "Uploaden",
        "newFolder": "Nieuwe map",
        "empty": "Het is hier wat leeg...",
        "name": "Naam",
        "size": "Grootte",
        "modified": "Laatst aangepast",
        "preview": "Voorbeeld",
        "edit": "Als tekst bewerken",
        "rename": "Hernoemen",
        "move": "Verplaatsen",
        "copy": "Kopiëren",
        "delete": "Verwijderen",
        "download": "Downloaden",
        "share": "Delen",
        "save": "Wijzigingen opslaan",
        "editor": "Als tekst bewerken",
        "noPreview": "Geen voorbeeld beschikbaar voor dit bestand.",
        "clearSearch": "Wissen"
      },
      "shares": {
        "title": "Beheer van gedeelde mappen en bestanden",
        "path": "Pad",
        "password": "Optioneel wachtwoord",
        "copy": "Download-link kopiëren naar klembord",
        "download": "Downloaden"
      },
      "settings": {
        "title": "Instellingen",
        "theme": "Thema",
        "language": "Taal",
        "light": "Licht",
        "dark": "Donker",
        "system": "Systeem standaard",
        "password": "Wachtwoord wijzigen",
        "currentPassword": "Uw huidige wachtwoord",
        "newPassword": "Uw nieuwe wachtwoord",
        "changePassword": "Wachtwoord wijzigen",
        "save": "Opslaan"
      },
      "common": {
        "cancel": "Annuleren",
        "create": "Aanmaken",
        "close": "Sluiten",
        "loading": "Laden...",
        "copied": "Link gekopieerd!",
        "error": "Er ging iets fout"
      }
    }
  },
  "nl-BE": {
    "translation": {
      "nav": {
        "files": "Bestanden",
        "settings": "Instellingen",
        "logout": "Uitloggen"
      },
      "auth": {
        "username": "Gebruikersnaam",
        "password": "Wachtwoord",
        "signIn": "Log in",
        "failed": "Verkeerde inloggegevens",
        "newPassword": "Uw nieuw wachtwoord",
        "confirmPassword": "Bevestig uw nieuw wachtwoord"
      },
      "files": {
        "search": "Zoeken...",
        "upload": "Uploaden",
        "newFolder": "Nieuwe map",
        "empty": "Het is hier wat leeg...",
        "name": "Naam",
        "size": "Grootte",
        "modified": "Laatst bewerkt",
        "rename": "Hernoemen",
        "move": "Verplaatsen",
        "copy": "Kopiëren",
        "delete": "Verwijderen",
        "download": "Downloaden",
        "share": "Delen",
        "clearSearch": "Wissen"
      },
      "shares": {
        "download": "Downloaden"
      },
      "settings": {
        "title": "Instellingen",
        "language": "Taal",
        "password": "Wijzig Wachtwoord",
        "newPassword": "Uw nieuw wachtwoord",
        "changePassword": "Wijzig Wachtwoord",
        "save": "Opslaan"
      },
      "common": {
        "cancel": "Annuleren",
        "create": "Aanmaken",
        "close": "Sluiten",
        "loading": "Laden...",
        "copied": "Link gekopieerd!",
        "error": "Er ging iets fout"
      }
    }
  },
  "no": {
    "translation": {
      "nav": {
        "files": "Filer",
        "settings": "Innstillinger",
        "logout": "Logg Ut"
      },
      "auth": {
        "username": "Brukernavn",
        "password": "Passord",
        "signIn": "Logg inn",
        "failed": "Feil legitimasjon",
        "newPassword": "Sett ditt nye passord",
        "confirmPassword": "Bekreft ditt nye passord"
      },
      "files": {
        "search": "Søk...",
        "upload": "Last opp",
        "newFolder": "Ny mappe",
        "empty": "Det føltes ensomt her...",
        "name": "Navn",
        "size": "Størrelse",
        "modified": "Sist endret",
        "preview": "Forhåndsvisning",
        "rename": "Gi nytt navn",
        "move": "Flytt",
        "copy": "Kopier",
        "delete": "Slett",
        "download": "Nedlast",
        "share": "Del",
        "save": "Lagre Endringane ",
        "noPreview": "Forhåndsvisning er ikkje tilgjengeleg for denne filen.",
        "clearSearch": "Fjern"
      },
      "shares": {
        "title": "Del Ledelse",
        "path": "Veg",
        "password": "Valgfritt passord",
        "copy": "Kopier nedlastingslenken til utklippstavlen",
        "download": "Nedlast"
      },
      "settings": {
        "title": "Innstillinger",
        "theme": "Tema",
        "language": "Språk",
        "light": "Lyst",
        "dark": "Mørk",
        "system": "Systemstandard",
        "password": "Skift Passord",
        "newPassword": "Sett ditt nye passord",
        "changePassword": "Skift Passord",
        "save": "Lagre"
      },
      "common": {
        "cancel": "Avbryt",
        "create": "Opprett",
        "close": "Lukk",
        "confirm": "Ok",
        "loading": "Laster....",
        "copied": "Link koppiert!",
        "error": "Noko gikk galt."
      }
    }
  },
  "pl": {
    "translation": {
      "nav": {
        "files": "Pliki",
        "settings": "Ustawienia",
        "logout": "Wyloguj"
      },
      "auth": {
        "username": "Nazwa użytkownika",
        "password": "Hasło",
        "signIn": "Zaloguj",
        "failed": "Błędne dane logowania",
        "newPassword": "Nowe hasło",
        "confirmPassword": "Potwierdź nowe hasło"
      },
      "files": {
        "search": "Szukaj...",
        "upload": "Wyślij",
        "newFolder": "Nowy folder",
        "empty": "Smutno, gdy tak pusto...",
        "name": "Nazwa",
        "size": "Rozmiar",
        "modified": "Ostatnio zmodyfikowano",
        "preview": "Podgląd",
        "edit": "Edytuj jako tekst",
        "rename": "Zmień nazwę",
        "move": "Przenieś",
        "copy": "Kopiuj",
        "delete": "Usuń",
        "download": "Pobierz",
        "share": "Udostępnij",
        "save": "Zapisz zmiany",
        "editor": "Edytuj jako tekst",
        "noPreview": "Podgląd tego pliku jest niedostępny.",
        "clearSearch": "Wyczyść"
      },
      "shares": {
        "title": "Zarządzanie udostępnianiem",
        "path": "Ścieżka",
        "password": "Opcjonalne hasło",
        "copy": "Kopiuj link pobierania do schowka",
        "download": "Pobierz"
      },
      "settings": {
        "title": "Ustawienia",
        "theme": "Motyw",
        "language": "Język",
        "light": "Jasny",
        "dark": "Ciemny",
        "system": "Domyślny systemowy",
        "password": "Zmień hasło",
        "currentPassword": "Twoje aktualne hasło",
        "newPassword": "Nowe hasło",
        "changePassword": "Zmień hasło",
        "save": "Zapisz"
      },
      "common": {
        "cancel": "Anuluj",
        "create": "Utwórz",
        "close": "Zamknij",
        "loading": "Ładowanie...",
        "copied": "Link skopiowany!",
        "error": "Pojawił się jakiś błąd"
      }
    }
  },
  "pt-BR": {
    "translation": {
      "nav": {
        "files": "Arquivos",
        "settings": "Configurações",
        "logout": "Sair"
      },
      "auth": {
        "username": "Nome do usuário",
        "password": "Senha",
        "failed": "Ops! Dados incorretos.",
        "newPassword": "Nova senha",
        "confirmPassword": "Confirme a nova senha"
      },
      "files": {
        "search": "Pesquise...",
        "upload": "Enviar",
        "newFolder": "Nova pasta",
        "empty": "Não existe nada aqui.",
        "name": "Nome",
        "size": "Tamanho",
        "modified": "Última modificação",
        "rename": "Renomear",
        "move": "Mover",
        "copy": "Copiar",
        "delete": "Apagar",
        "download": "Baixar",
        "share": "Compartilhar",
        "noPreview": "Pré-visualização não disponível para este arquivo.",
        "clearSearch": "Limpar"
      },
      "shares": {
        "title": "Gerenciamento do compartilhamento",
        "password": "Senha opcional",
        "download": "Baixar"
      },
      "settings": {
        "title": "Configurações",
        "theme": "Tema",
        "language": "Idioma",
        "light": "Claro",
        "dark": "Escuro",
        "password": "Alterar senha",
        "newPassword": "Nova senha",
        "changePassword": "Alterar senha",
        "save": "Salvar"
      },
      "common": {
        "cancel": "Cancelar",
        "create": "Criar",
        "close": "Fechar",
        "loading": "Carregando. Aguarde, por favor.",
        "copied": "Link copiado!",
        "error": "Algo de errado ocorreu"
      }
    }
  },
  "pt-PT": {
    "translation": {
      "nav": {
        "files": "Ficheiros",
        "settings": "Definições",
        "logout": "Sair"
      },
      "auth": {
        "username": "Nome de utilizador",
        "password": "Palavra-passe",
        "signIn": "Entrar",
        "failed": "Credenciais erradas",
        "newPassword": "A sua nova palavra-passe",
        "confirmPassword": "Confirmar a sua palavra-passe"
      },
      "files": {
        "search": "Procurar...",
        "upload": "Enviar",
        "newFolder": "Nova pasta",
        "empty": "Sinto-me sózinho...",
        "name": "Nome",
        "size": "Tamanho",
        "modified": "Última modificação",
        "preview": "Pré-visualizar",
        "edit": "Editar como Texto",
        "rename": "Mudar o nome",
        "move": "Mover",
        "copy": "Copiar",
        "delete": "Eliminar",
        "download": "Descarregar",
        "share": "Partilhar",
        "save": "Guardar alterações",
        "editor": "Editar como Texto",
        "noPreview": "Pré-visualização não disponível para este ficheiro.",
        "clearSearch": "Limpar"
      },
      "shares": {
        "title": "Gestão de Partilhas",
        "path": "Caminho",
        "password": "Palavra-passe opcional",
        "copy": "Copiar link do download para a área de transferência",
        "download": "Descarregar"
      },
      "settings": {
        "title": "Definições",
        "theme": "Tema",
        "language": "Idioma",
        "light": "Claro",
        "dark": "Escuro",
        "system": "Predefinição do sistema",
        "password": "Alterar Palavra-passe",
        "currentPassword": "A Sua Palavra-passe Actual",
        "newPassword": "A sua nova palavra-passe",
        "changePassword": "Alterar Palavra-passe",
        "save": "Guardar"
      },
      "common": {
        "cancel": "Cancelar",
        "create": "Criar",
        "close": "Fechar",
        "loading": "A carregar...",
        "copied": "Link copiado!",
        "error": "Algo correu mal."
      }
    }
  },
  "ro": {
    "translation": {
      "nav": {
        "files": "Fișiere",
        "settings": "Setări"
      },
      "auth": {
        "username": "Utilizator",
        "password": "Parola",
        "signIn": "Autentificare",
        "failed": "Informații greșite",
        "newPassword": "Noua ta parolă",
        "confirmPassword": "Confirmă noua parolă"
      },
      "files": {
        "search": "Caută...",
        "upload": "Încarcă",
        "newFolder": "Director nou",
        "empty": "Nu este nimic aici...",
        "name": "Nume",
        "size": "Dimensiune",
        "modified": "Ultima modificare",
        "rename": "Redenumește",
        "move": "Mută",
        "copy": "Copiază",
        "delete": "Șterge",
        "download": "Descarcă",
        "share": "Distribuie",
        "clearSearch": "Curăță"
      },
      "shares": {
        "download": "Descarcă"
      },
      "settings": {
        "title": "Setări",
        "language": "Limba",
        "password": "Schimbă parola",
        "newPassword": "Noua ta parolă",
        "changePassword": "Schimbă parola",
        "save": "Salvează"
      },
      "common": {
        "cancel": "Anulează",
        "create": "Crează",
        "close": "Închide",
        "loading": "Se încarcă...",
        "copied": "Legătură copiată!",
        "error": "Ceva n-a funcționat cum trebuie"
      }
    }
  },
  "ru": {
    "translation": {
      "nav": {
        "files": "Файлы",
        "settings": "Настройки",
        "logout": "Выйти"
      },
      "auth": {
        "username": "Имя пользователя",
        "password": "Пароль",
        "signIn": "Войти",
        "failed": "Неверные данные",
        "newPassword": "Новый пароль",
        "confirmPassword": "Повтор нового пароля"
      },
      "files": {
        "search": "Поиск...",
        "upload": "Загрузить",
        "newFolder": "Новый каталог",
        "empty": "Здесь пусто...",
        "name": "Имя",
        "size": "Размер",
        "modified": "Последнее изменение",
        "preview": "Предпросмотр",
        "edit": "Редактировать как текст",
        "rename": "Переименовать",
        "move": "Переместить",
        "copy": "Копировать",
        "delete": "Удалить",
        "download": "Скачать",
        "share": "Поделиться",
        "save": "Сохранить",
        "editor": "Редактировать как текст",
        "noPreview": "Предварительный просмотр для этого файла недоступен.",
        "clearSearch": "Очистить"
      },
      "shares": {
        "title": "Управление расшаренными ссылками",
        "path": "Путь",
        "password": "Необязательный пароль",
        "copy": "Скопировать ссылку в буфер",
        "download": "Скачать"
      },
      "settings": {
        "title": "Настройки",
        "theme": "Тема",
        "language": "Язык",
        "light": "Светлая",
        "dark": "Темная",
        "system": " Системные настройки по умолчанию",
        "password": "Изменение пароля",
        "newPassword": "Новый пароль",
        "changePassword": "Изменение пароля",
        "save": "Сохранить"
      },
      "common": {
        "cancel": "Отмена",
        "create": "Создать",
        "close": "Закрыть",
        "loading": "Загрузка...",
        "copied": "Ссылка скопирована!",
        "error": "Ошибка"
      }
    }
  },
  "sk": {
    "translation": {
      "nav": {
        "files": "Súbory",
        "settings": "Nastavenia",
        "logout": "Odhlásiť"
      },
      "auth": {
        "username": "Používateľské meno",
        "password": "Heslo",
        "signIn": "Prihlásiť",
        "failed": "Nesprávne prihlasovacie údaje",
        "newPassword": "Nové heslo",
        "confirmPassword": "Potvrdenie nového hesla"
      },
      "files": {
        "search": "Hľadať...",
        "upload": "Nahrať",
        "newFolder": "Nový priečinok",
        "empty": "Je tu tak pusto...",
        "name": "Názov",
        "size": "Veľkosť",
        "modified": "Posledná zmena",
        "preview": "Náhľad",
        "rename": "Premenovať",
        "move": "Presunúť",
        "copy": "Kopírovať",
        "delete": "Odstrániť",
        "download": "Stiahnuť",
        "share": "Zdieľať",
        "save": "Uložiť zmeny",
        "noPreview": "Pre tento súbor nie je dostupný náhľad.",
        "clearSearch": "Zrušiť výber"
      },
      "shares": {
        "title": "Správa zdieľania",
        "path": "Cesta",
        "password": "Voliteľné heslo",
        "copy": "Kopírovať odkaz na stiahnutie do schránky",
        "download": "Stiahnuť"
      },
      "settings": {
        "title": "Nastavenia",
        "theme": "Téma",
        "language": "Jazyk",
        "light": "Svetlá",
        "dark": "Tmavá",
        "system": "Predvolené nastavenie systému",
        "password": "Zmeniť heslo",
        "newPassword": "Nové heslo",
        "changePassword": "Zmeniť heslo",
        "save": "Uložiť"
      },
      "common": {
        "cancel": "Zrušiť",
        "create": "Vytvoriť",
        "close": "Zavrieť",
        "loading": "Načítanie...",
        "copied": "Odkaz skopírovaný!",
        "error": "Niečo sa pokazilo"
      }
    }
  },
  "sv-SE": {
    "translation": {
      "nav": {
        "files": "Filer",
        "settings": "Inställningar",
        "logout": "Logga ut"
      },
      "auth": {
        "username": "Användarnamn",
        "password": "Lösenord",
        "signIn": "Logga in",
        "failed": "Fel inloggning",
        "newPassword": "Ditt nya lösenord",
        "confirmPassword": "Bekräfta ditt nya lösenord"
      },
      "files": {
        "search": "Sök...",
        "upload": "Ladda upp",
        "newFolder": "Ny mapp",
        "empty": "Väldigt ensamt här....",
        "name": "Namn",
        "size": "Storlek",
        "modified": "Senast ändrad",
        "preview": "Förhandsvisa",
        "rename": "Ändra namn",
        "move": "Flytta",
        "copy": "Kopiera",
        "delete": "Ta bort",
        "download": "Ladda ner",
        "share": "Dela",
        "save": "Spara ändringar",
        "noPreview": "Förhandsvisning är inte tillgänglig för denna fil.",
        "clearSearch": "Rensa"
      },
      "shares": {
        "title": "Utdelningshantering",
        "path": "Sökväg",
        "password": "Valfritt lösenord",
        "copy": "Kopiera hämtningslänk till urklipp",
        "download": "Ladda ner"
      },
      "settings": {
        "title": "Inställningar",
        "theme": "Tema",
        "language": "Språk",
        "light": "Ljus",
        "dark": "Mörk",
        "system": "Systemet standard",
        "password": "Ändra lösenord",
        "newPassword": "Ditt nya lösenord",
        "changePassword": "Ändra lösenord",
        "save": "Spara"
      },
      "common": {
        "cancel": "Avbryt",
        "create": "Skapa",
        "close": "Stäng",
        "loading": "Laddar.....",
        "copied": "Länk kopierad",
        "error": "Något gick fel"
      }
    }
  },
  "tr": {
    "translation": {
      "nav": {
        "files": "Dosyalar",
        "settings": "Ayarlar",
        "logout": "Çıkış"
      },
      "auth": {
        "username": "Kullanıcı adı",
        "password": "Şifre",
        "signIn": "Giriş",
        "failed": "Yanlış hesap bilgileri",
        "newPassword": "Yeni şifre",
        "confirmPassword": "Yeni şifre tekrarı"
      },
      "files": {
        "search": "Ara...",
        "upload": "Yükle",
        "newFolder": "Yeni klasör",
        "empty": "Burada yalnızlık hissediyorum...",
        "name": "İsim",
        "size": "Boyut",
        "modified": "Son güncellenme",
        "rename": "Yeniden anlandır",
        "move": "Taşı",
        "copy": "Kopyala",
        "delete": "Sil",
        "download": "İndir",
        "share": "Paylaş",
        "noPreview": "Bu dosya için önizleme aktif değil",
        "clearSearch": "Temizle"
      },
      "shares": {
        "title": "Paylaşım yönetimi",
        "path": "Yol",
        "password": "İsteğe bağlı şifre",
        "download": "İndir"
      },
      "settings": {
        "title": "Ayarlar",
        "language": "Dil",
        "password": "Şifre Değiştir",
        "newPassword": "Yeni şifre",
        "changePassword": "Şifre Değiştir",
        "save": "Kaydet"
      },
      "common": {
        "cancel": "Vazgeç",
        "create": "Oluştur",
        "close": "Kapat",
        "confirm": "Tamam",
        "loading": "Yükleniyor...",
        "copied": "Link kopyalandı!",
        "error": "Bir şeyler yanlış gitti"
      }
    }
  },
  "uk": {
    "translation": {
      "nav": {
        "files": "Файли",
        "settings": "Налаштування",
        "logout": "Вийти"
      },
      "auth": {
        "username": "Ім'я користувача",
        "password": "Пароль",
        "signIn": "Увійти",
        "failed": "Неправильне ім'я користувача або пароль",
        "newPassword": "Новий пароль",
        "confirmPassword": "Підтвердження нового пароля"
      },
      "files": {
        "search": "Пошук...",
        "upload": "Вивантажити",
        "newFolder": "Новий каталог",
        "empty": "Тут порожньо...",
        "name": "Ім'я",
        "size": "Розмір",
        "modified": "Останній раз змінено",
        "preview": "Попередній перегляд",
        "rename": "Перейменувати",
        "move": "Перемістити",
        "copy": "Копіювати",
        "delete": "Видалити",
        "download": "Завантажити",
        "share": "Поділитися",
        "noPreview": "Попередній перегляд для цього файлу недоступний.",
        "clearSearch": "Очистити"
      },
      "shares": {
        "title": "Управління спільними посиланнями",
        "path": "Шлях",
        "password": "Необов'язковий пароль",
        "copy": "Скопіювати завантажувальне посилання в буфер обміну",
        "download": "Завантажити"
      },
      "settings": {
        "title": "Налаштування",
        "theme": "Тема",
        "language": "Мова",
        "light": "Світла",
        "dark": "Темна",
        "system": "За замовчуванням (системна)",
        "password": "Зміна пароля",
        "newPassword": "Новий пароль",
        "changePassword": "Зміна пароля",
        "save": "Зберегти"
      },
      "common": {
        "cancel": "Відмінити",
        "create": "Створити",
        "close": "Закрити",
        "confirm": "ОК",
        "loading": "Завантаження...",
        "copied": "Посилання скопійоване!",
        "error": "Помилка"
      }
    }
  },
  "vi": {
    "translation": {
      "nav": {
        "files": "Tập tin",
        "settings": "Cài đặt",
        "logout": "Đăng xuất"
      },
      "auth": {
        "username": "Tên người dùng",
        "password": "Mật khẩu",
        "signIn": "Đăng nhập",
        "failed": "Thông tin đăng nhập không đúng",
        "newPassword": "Mật khẩu mới của bạn",
        "confirmPassword": "Xác nhận mật khẩu mới"
      },
      "files": {
        "search": "Tìm kiếm...",
        "upload": "Tải lên",
        "newFolder": "Thư mục mới",
        "empty": "Không có gì ở đây...",
        "name": "Tên",
        "size": "Kích thước",
        "modified": "Sửa đổi lần cuối",
        "preview": "Xem trước",
        "rename": "Đổi tên",
        "move": "Di chuyển",
        "copy": "Sao chép",
        "delete": "Xóa",
        "download": "Tải xuống",
        "share": "Chia sẻ",
        "noPreview": "Không có bản xem trước cho tập tin này.",
        "clearSearch": "Xóa"
      },
      "shares": {
        "title": "Quản lý chia sẻ",
        "path": "Đường dẫn",
        "password": "Mật khẩu tùy chọn",
        "copy": "Sao chép liên kết tải xuống vào clipboard",
        "download": "Tải xuống"
      },
      "settings": {
        "title": "Cài đặt",
        "theme": "Chủ đề",
        "language": "Ngôn ngữ",
        "light": "Sáng",
        "dark": "Tối",
        "system": "Mặc định hệ thống",
        "password": "Đổi mật khẩu",
        "newPassword": "Mật khẩu mới của bạn",
        "changePassword": "Đổi mật khẩu",
        "save": "Lưu"
      },
      "common": {
        "cancel": "Hủy",
        "create": "Tạo",
        "close": "Đóng",
        "loading": "Đang tải...",
        "copied": "Liên kết đã được sao chép!",
        "error": "Đã xảy ra lỗi"
      }
    }
  },
  "zh-CN": {
    "translation": {
      "nav": {
        "files": "文件",
        "settings": "设置",
        "logout": "退出"
      },
      "auth": {
        "username": "用户名",
        "password": "密码",
        "signIn": "登录",
        "failed": "用户名或密码错误",
        "newPassword": "新密码",
        "confirmPassword": "再次输入新密码"
      },
      "files": {
        "search": "搜索...",
        "upload": "上传",
        "newFolder": "新建文件夹",
        "empty": "暂无任何文件...",
        "name": "名称",
        "size": "大小",
        "modified": "修改时间",
        "preview": "预览",
        "edit": "以文本模式编辑",
        "rename": "重命名",
        "move": "移动",
        "copy": "复制",
        "delete": "删除",
        "download": "下载",
        "share": "分享",
        "save": "保存更改",
        "editor": "以文本模式编辑",
        "noPreview": "该文件暂不支持预览",
        "clearSearch": "清空"
      },
      "shares": {
        "title": "分享管理",
        "path": "路径",
        "password": "密码（选填，留空则无需密码）",
        "copy": "复制下载链接到剪贴板",
        "download": "下载"
      },
      "settings": {
        "title": "设置",
        "theme": "主题",
        "language": "语言",
        "light": "浅色",
        "dark": "深色",
        "system": "系统默认",
        "password": "更改密码",
        "currentPassword": "当前密码",
        "newPassword": "新密码",
        "changePassword": "更改密码",
        "save": "保存"
      },
      "common": {
        "cancel": "取消",
        "create": "创建",
        "close": "关闭",
        "confirm": "确定",
        "loading": "加载中...",
        "copied": "链接已复制！",
        "error": "出现未知错误..."
      }
    }
  },
  "zh-TW": {
    "translation": {
      "nav": {
        "files": "檔案",
        "settings": "設定",
        "logout": "登出"
      },
      "auth": {
        "username": "帳號",
        "password": "密碼",
        "signIn": "登入",
        "failed": "帳號或密碼錯誤",
        "newPassword": "您的新密碼",
        "confirmPassword": "重輸一遍新密碼"
      },
      "files": {
        "search": "搜尋...",
        "upload": "上傳",
        "newFolder": "建立資料夾",
        "empty": "這裡沒有任何檔案...",
        "name": "名稱",
        "size": "大小",
        "modified": "最後修改",
        "preview": "預覽",
        "rename": "重新命名",
        "move": "移動",
        "copy": "複製",
        "delete": "刪除",
        "download": "下載",
        "share": "分享",
        "noPreview": "此檔案無法預覽。",
        "clearSearch": "清空"
      },
      "shares": {
        "title": "分享管理",
        "path": "路徑",
        "password": "密碼（選填，不填即無密碼）",
        "copy": "複製到剪貼簿",
        "download": "下載"
      },
      "settings": {
        "title": "設定",
        "theme": "主題",
        "language": "語言",
        "light": "淺色",
        "dark": "深色",
        "system": "系統預設",
        "password": "更改密碼",
        "newPassword": "您的新密碼",
        "changePassword": "更改密碼",
        "save": "儲存"
      },
      "common": {
        "cancel": "取消",
        "create": "建立",
        "close": "關閉",
        "confirm": "確認",
        "loading": "讀取中...",
        "copied": "連結已複製！",
        "error": "發出了一點錯誤..."
      }
    }
  }
} as const
